name: "Issue/PR labeler"

on:
  - pull_request
  - issues

permissions:
  issues: write
  pull-requests: write

jobs:
  triage:
    runs-on: ubuntu-latest
    steps:
      - name: auto-label by path
        uses: actions/labeler@v7
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          configuration-path: .github/labeler.yml
