name: Release notes

on:
  push:
    branches: [main]
  pull_request:
    types: [closed]

permissions:
  contents: write
  pull-requests: read

jobs:
  update-draft-release:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - uses: release-drafter/release-drafter@v6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
